!
!  ConsoleApp.f90
!
!  Fortran Console Application 
!  Generated by PGI Visual Fortran(R)
!  10/25/2009 5:31:15 PM
!

      program main

      implicit none

      ! Variables

      character*30 myline1
      character*30 myline2
	  character*30 winfile
	  integer i

	  winfile="C:\\arp.txt"
      ! Body
      
      open(unit=1, file=winfile)
      read(1,*) myline1
      read(1,*) myline2
      close(1)
      !WRITE(UNIT=*, FMT=*) 'Hello World'
      !write(*,*) 'Before PAUSE'
      write(*,*) myline1
      write(*,*) myline2
      !pause
      !write (*,*) 'After PAUSE'
      !CALL SYSTEM('arp -s 192.168.2.1 aa-bb-cc-dd-ee-ff')
      CALL SYSTEM('arp -s '//myline1//' '//myline2)

      end program main